global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'ether-ai'
    static_configs:
      - targets: ['ether-ai:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    
  - job_name: 'system'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 10s
    
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Storage retention
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
